cloud: aws
account:
  id: "891377122094"         # Replace with your AWS account ID
  region: "us-east-1"
  environment: "dev"
email:
  to: "admin@example.com"    # Replace with your email
cluster:
  name: "test-eks-cluster"
  version: "1.29"
  chartVersion: "1.0"
nodeGroups:
  - name: apps
    instanceType: t3.medium
    min: 2
    max: 3
    desired: 2
    subnets:
      - subnet-12345678       # Optional if using default VPC
      - subnet-87654321
    labels:
      role: apps
    shutdownDelay:
      enabled: true
      delay: 300
addons:
  ingressNginx:
    enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
  certificateOperator:
    enabled: false
  cilium:
    enabled: false
  cloudwatchLogs:
    enabled: true
    retentionInDays: 30
  flux:
    enabled: false
identityProvider:
  enabled: false
kubeletConfiguration:
  shutdownGracePeriod: "30s"
  shutdownGracePeriodCriticalPods: "10s"
nodeUpdates:
  enabled: true
  schedule: "0 2 * * *"  # 2 AM every day
  drainTimeout: "5m"
  partitionSize: 1
